org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.20
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=intangible
mod_name=Intangible
mod_license=MIT
mod_version=1.0.3
mod_group_id=io.github.shrhang
mod_authors=ShrHang
mod_description=Added an effect that allows players slow flight and wall phasing.

jei_version = 15.20.0.106
